[package]
name = "dagrs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.5"
bimap = "0.6.1"
deno_core = "0.191.0"
clap = { version = "4.2.2", features = ["derive"] }
anymap2 = "0.13.0"
thiserror = "1.0.30"
tokio = { version = "1.28", features = ["rt", "sync","rt-multi-thread"] }
log = "0.4"
simplelog = "0.12"